---
title: "PlottingThings"
author: "Alexa Dudek"
date: "12/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries}
library(ggplot2)
```


```{r Initial Perretti Model Test Plots}

# get mean from last 20 time steps
meanX20 = mean(testPopulations1$x[30:50])
meanY20 = mean(testPopulations1$y[30:50])

ggplot(testPopulations1, aes(x = time, y = x)) + 
  geom_line() +
  geom_function(fun = function(x) meanX20, color = "blue") +
  theme_bw() + 
  labs(x = "Time Step", y = "Population", title = "Forage Fish Simulated Time Series")

ggplot(testPopulations1, aes(x = time, y = y)) + 
  geom_line() +
  geom_function(fun = function(x) meanY20, color = "blue") +
  theme_bw() + 
  labs(x = "Time Step", y = "Population", title = "Predator Fish Simulated Time Series")

ggplot(testPopulations1, aes(x = x, y = y)) + 
  geom_line() +
  theme_bw() + 
  labs(x = "Forage Fish", y = "Predator", title = "Tradeoff?")

```


```{r Trade Off Analysis Test 1 Plot}
testTradeOff1Plot <- ggplot(testTradeOff1, aes(x = FmX, y = FmY, z = yBiomass)) +
  geom_contour_filled() +
  labs(x = "Forage Fish Fishing Mortality", y = "Predator Fishing Mortality", title = "Trade Off Contour Analysis")

testTradeOff2Plot <- ggplot(testTradeOff2, aes(x = FmX, y = FmY, z = yBiomass)) +
  geom_contour_filled() +
  labs(x = "Forage Fish Fishing Mortality", y = "Predator Fishing Mortality", title = "Trade Off Contour Analysis on 200 years")

print(testTradeOff2Plot)

print(testTradeOff1Plot)
```

```{r}
# simulatePopulations_noise <- function(x0, y0, rx, ry, Kx, Ky, c, fx, fy, numTimeSteps = 50)


plotTests <- function(dataframe) {
  forageFishPlot <- ggplot(dataframe, aes(x = time, y = x)) + 
    geom_line() +
    geom_function(fun = function(x) mean(dataframe$x), color = "blue") +
    theme_bw() + 
    labs(x = "Time Step", y = "Population", title = "Forage Fish Simulated Time Series")
  
  predatorPlot <- ggplot(dataframe, aes(x = time, y = y)) + 
    geom_line() +
    geom_function(fun = function(x) mean(dataframe$y), color = "blue") +
    theme_bw() + 
    labs(x = "Time Step", y = "Population", title = "Predator Fish Simulated Time Series")
  
  bothPlot <- ggplot(dataframe, aes(x = x, y = y)) + 
    geom_line() +
    theme_bw() + 
    labs(x = "Forage Fish", y = "Predator", title = "Tradeoff?")
  
  print(forageFishPlot)
  print(predatorPlot)
  print(bothPlot)
}

varySBGrowthRateTest = simulatePopulations_noise(0.4, 0.4, 3.8, 2.5, 1.0, 1.0, 0.1, 0.2, 0.2, 50)

plotTests(varySBGrowthRateTest)

```

```{r Plot Trade Off Tests}

plotTradeOff <- function(dataframe){
  plot <- ggplot(dataframe, aes(x = FmX, y = FmY, z = yBiomass)) +
    geom_contour_filled() + geom_contour(color="grey")+
    geom_contour(color="black",breaks=0.58)+
    labs(x = "Forage Fish Fishing Mortality", y = "Predator Fishing Mortality", title = "Trade Off Contour Analysis")
  print(plot)
}

# generateTradeOffData <- function(FmListX, FmListY, x0, y0, rx, ry, Kx, Ky, c, numTimeSteps = 50, numMeanYears = 20)

FmListX = seq(0, 0.2, by = 0.01) 
FmListY = seq(0, 0.2, by = 0.01)

varySBGrowthRateTO <- generateTradeOffData(FmListX, FmListY, 0.4, 0.4, 3.8, 2.5, 1.0, 1.0, 0.1, 50, 50)
plotTradeOff(varySBGrowthRateTO)

```

